name: CI-CD-Pipeline-to-AWS-Elastic-Beanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "schatten-flask-application-packages"
  EB_APPLICATION_NAME: "MyFlask"
  EB_ENVIRONMENT_NAME: "MyFlask-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{GITHUB_SHA}}.zip"
  AWS_REGION_NAME: "eu-north-1"

on:
  push:
    branches:
      - main
jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3

      - name: Create ZIP deployment package
        run:  zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git *
